services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/usr/src/app
    command: yarn dev
    expose:
      - '3000'

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/web/log:/var/log/nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
